# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='isDownloaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apps',
            name='downloaded',
            field=models.IntegerField(default=1),
        ),
    ]
