# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_auto_20160908_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapps',
            name='apps',
        ),
        migrations.DeleteModel(
            name='UserApps',
        ),
    ]
