# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0009_apps_appfilename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='downloaded',
        ),
        migrations.AlterField(
            model_name='apps',
            name='isDownloaded',
            field=models.BooleanField(default=False),
        ),
    ]
