# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_auto_20170103_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=50)),
                ('version', models.CharField(default='none', max_length=50)),
                ('updateTime', models.CharField(default='none', max_length=50)),
                ('size', models.CharField(default='none', max_length=50)),
                ('description', models.CharField(default='none', max_length=500)),
            ],
        ),
    ]
