# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_editions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
