# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0013_auto_20170111_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='appFileName',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='editions',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='editions',
            name='size',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='editions',
            name='updateTime',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='editions',
            name='version',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
