# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0016_auto_20170227_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
    ]
