# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0017_auto_20170227_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passport',
            new_name='password',
        ),
    ]
